services:
  app:
    build: .
    restart: always
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      # Perzistentni storage za bazu i slike izvan kontejnera
      - ./data:/app/data
      - ./.output:/app/.output
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - prometheus