global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'pothole_app'
    static_configs:
      # Fix: 'host.docker.internal' ne radi na Linux-u.
      # Unutar Docker mreze, servisi se adresiraju imenom iz compose.yaml.
      - targets: ['app:8000']